#!/usr/bin/env sh
#
# This script can be used to wrap any pre run logic
#
script_path="$(cd "$(dirname "$0")"; pwd -P)"
cd "$script_path"

export ANSIBLE_FILTER_PLUGINS="${ANSIBLE_LOOKUP_PLUGINS}:${script_path}/plugins/filters"
export ANSIBLE_LOOKUP_PLUGINS="${ANSIBLE_LOOKUP_PLUGINS}:${script_path}/plugins/lookup"

if [ ! -f src/ansible/__main__.py ]; then
    echo "ERR  Oops, looks like you have not installed the dependencies yet."
    echo "ERR  Run the install.sh script."
    exit 1
fi

target="src/$(basename "$0")"

if [[ ! -h "$target" && ! -d "$target" ]]; then
    echo "ERR  Ansible binary name $target does not exist or is invalid"
    exit 1
fi

if [[ "${1:-}" == "--version" && -f RELEASE ]]; then
    echo "ansible portable v$(head -1 RELEASE) ($(tail -1 RELEASE))"
fi

python "$target" $@
