#!/usr/bin/env sh
#
# This script can be used to wrap any pre run logic
#
script_path="$(cd "$(dirname "$0")"; pwd -P)"
cd "$script_path"

name="$(basename "$0")"

export ANSIBLE_FILTER_PLUGINS="${ANSIBLE_LOOKUP_PLUGINS}:${script_path}/plugins/filters"
export ANSIBLE_LOOKUP_PLUGINS="${ANSIBLE_LOOKUP_PLUGINS}:${script_path}/plugins/lookup"

python src/"$name" $@
